# Generated by Django 2.0.5 on 2018-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0003_auto_20180515_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='NewFeature'),
            preserve_default=False,
        ),
    ]
